name: Browser Automation with Puppeteer

on:
  push:
    branches:
      - main   # Trigger on push to main branch
  pull_request:
    branches:
      - main   # Trigger on PR to main branch

jobs:
  browser-test:
    runs-on: ubuntu-latest  # Choose the OS for the action runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository to the runner

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the appropriate Node.js version

    - name: Install Puppeteer
      run: |
        npm install puppeteer

    - name: Run Puppeteer script
      run: |
        echo "const puppeteer = require('puppeteer');" > script.js
        echo "puppeteer.launch({headless: true}).then(async browser => {" >> script.js
        echo "  const page = await browser.newPage();" >> script.js
        echo "  await page.goto('https://mail.google.com');" >> script.js
        echo "  await page.screenshot({path: 'example.png'});" >> script.js
        echo "  await browser.close();" >> script.js
        echo "});" >> script.js
        node script.js

    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: example.png  # Upload the screenshot taken by Puppeteer
