name: Run Neko Browser to Take Screenshot of Gmail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  neko_screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t neko-image .

    - name: Run Neko Browser to Take Screenshot
      run: |
         # Run Firefox in headless mode without X11 access
         docker run --rm -v $(pwd)/output:/output selenium/standalone-firefox:latest \
            bash -c "firefox --headless --screenshot --window-size=1280x1024 --url https://mail.google.com --output /output/screenshot.png"
            
    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: screenshot.png

