name: Install Neko Rooms

on:
  push:
    branches:
      - main   # You can specify the branch for the pipeline to run (e.g., main, develop, etc.)
  pull_request:
    branches:
      - main   # You can also trigger this on pull requests

jobs:
  install:
    runs-on: ubuntu-latest  # Choose the OS you want to run the pipeline on

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out your repository

    - name: Install necessary dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Download and run Neko Rooms installation script
      run: |
        wget -O neko-rooms.sh https://raw.githubusercontent.com/m1k1o/neko-rooms/master/traefik/install
        sudo bash neko-rooms.sh

