name: Run Neko Browser to Take Screenshot of Gmail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  neko_screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Xvfb and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          x11-xserver-utils \
          xvfb \
          x11-apps \
          wget \
          curl

    - name: Run Xvfb Server
      run: |
        # Start a virtual X server with DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 &

    - name: Run Neko Browser to Take Screenshot
      run: |
        # Set DISPLAY to use the virtual X server
        export DISPLAY=:99

        # Run Firefox in headless mode with Xvfb, disable GPU hardware acceleration
        docker run --rm -v $(pwd)/output:/output selenium/standalone-firefox:latest \
          bash -c "echo 'user_pref(\"gfx.webrender.enabled\", false);' >> /root/.mozilla/firefox/*default*/prefs.js && \
              echo 'user_pref(\"layers.acceleration.disabled\", true);' >> /root/.mozilla/firefox/*default*/prefs.js && \
              firefox --headless --no-remote --screenshot --window-size=1280x1024 --url https://mail.google.com --output /output/screenshot.png"
              
    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: ./output/screenshot.png
