name: Run Neko Browser to Take Screenshot of Gmail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  neko_screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Xvfb and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          x11-xserver-utils \
          xvfb \
          x11-apps \
          wget \
          curl

    - name: Run Xvfb Server
      run: |
        # Start a virtual X server with DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 &

    - name: Create a Custom Firefox Profile with Disabled GPU
      run: |
        # Set DISPLAY to use the virtual X server
        export DISPLAY=:99

        # Create a custom Firefox profile directory
        mkdir -p /tmp/firefox-profile

        # Create a custom prefs.js file with hardware acceleration disabled
        echo 'user_pref("gfx.webrender.enabled", false);' > /tmp/firefox-profile/prefs.js
        echo 'user_pref("layers.acceleration.disabled", true);' >> /tmp/firefox-profile/prefs.js
        echo 'user_pref("media.hardware-video-decoding.enabled", false);' >> /tmp/firefox-profile/prefs.js

    - name: Run Firefox to Take Screenshot with Custom Profile
      run: |
        # Set DISPLAY to use the virtual X server
        export DISPLAY=:99

        # Run Firefox with the custom profile (no GPU, hardware acceleration disabled)
        docker run --rm -v $(pwd)/output:/output -v /tmp/firefox-profile:/root/.mozilla/firefox/profiles/custom \
          selenium/standalone-firefox:latest \
          bash -c "firefox --headless --no-remote --screenshot --window-size=1280x1024 --url https://mail.google.com --output /output/screenshot.png -P custom"

    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: ./output/screenshot.png
